
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import os

file_name = "C:/Users/AbhishekKonge/Downloads/Foundation Chemistry for Class X Part A standard 10 for IIT JEE Foundation ( PDFDrive ).pdf.crdownload"

file_stats = os.stat(file_name)

print(f'File Size in MegaBytes is {round((file_stats.st_size / (1024 * 1024)),1)} MB')
print((file_stats.st_size))
print(type(file_stats))


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("574x287")
window.configure(bg="#FFFFFF")

import string
a = "what Happened to you?"
# a = ' '.join(a.title() for a in a.split())
print(a.title())

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=287,
    width=574,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)
print(((1)))
canvas.place(x=0, y=0)
canvas.create_text(
    27.600372314453125,
    96.34383392333984,
    anchor="nw",
    text="Author",
    fill="#000000",
    font=("Abel Regular", 20 * -1)
)

canvas.create_text(
    32.243743896484375,
    28.401931762695312,
    anchor="nw",
    text="Book",
    fill="#000000",
    font=("Abel Regular", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    316.0,
    38.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=94.0,
    y=28.0,
    width=444.0,
    height=23.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    316.0,
    106.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=94.0,
    y=96.0,
    width=444.0,
    height=23.0
)

download_info = canvas.create_text(
    191.0,
    153.0,
    anchor="nw",
    text="Download a Book ;)",
    fill="#000000",
    font=("Abel Regular", 20 * -1)
)

def btn_click():
    canvas.itemconfig(download_info, text="Please Wait...")
    print(("asdasdads"))


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    # lambda: print("button_1 clicked"),
    command= btn_click,
    relief="flat"
)
button_1.place(
    x=200.0,
    y=211.0,
    width=174.8668212890625,
    height=43.995155334472656
)

# download_info = canvas.create_text(
#     191.0,
#     153.0,
#     anchor="nw",
#     text="Download a Book ;)",
#     fill="#000000",
#     font=("Abel Regular", 20 * -1)
# )
window.resizable(False, False)
window.mainloop()
